/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MinhasCandidaturasRouteImport } from './routes/minhas-candidaturas'
import { Route as RhRouteImport } from './routes/rh'
import { Route as VagasJobIdRouteImport } from './routes/vagas.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasCandidaturasRoute = MinhasCandidaturasRouteImport.update({
  id: '/minhas-candidaturas',
  path: '/minhas-candidaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasJobIdRoute = VagasJobIdRouteImport.update({
  id: '/vagas/$jobId',
  path: '/vagas/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minhas-candidaturas': typeof MinhasCandidaturasRoute
  '/rh': typeof RhRoute
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minhas-candidaturas': typeof MinhasCandidaturasRoute
  '/rh': typeof RhRoute
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/minhas-candidaturas': typeof MinhasCandidaturasRoute
  '/rh': typeof RhRoute
  '/vagas/$jobId': typeof VagasJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/minhas-candidaturas' | '/rh' | '/vagas/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/minhas-candidaturas' | '/rh' | '/vagas/$jobId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/minhas-candidaturas'
    | '/rh'
    | '/vagas/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MinhasCandidaturasRoute: typeof MinhasCandidaturasRoute
  RhRoute: typeof RhRoute
  VagasJobIdRoute: typeof VagasJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-candidaturas': {
      id: '/minhas-candidaturas'
      path: '/minhas-candidaturas'
      fullPath: '/minhas-candidaturas'
      preLoaderRoute: typeof MinhasCandidaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$jobId': {
      id: '/vagas/$jobId'
      path: '/vagas/$jobId'
      fullPath: '/vagas/$jobId'
      preLoaderRoute: typeof VagasJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MinhasCandidaturasRoute: MinhasCandidaturasRoute,
  RhRoute: RhRoute,
  VagasJobIdRoute: VagasJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
